# Generated by Django 2.2.2 on 2019-06-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
