# Generated by Django 2.2.2 on 2019-06-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='은정리 hi', max_length=50)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(max_length=500)),
            ],
        ),
    ]
