# Generated by Django 2.2.2 on 2019-06-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='body',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='none', upload_to='images/'),
        ),
    ]
