# Generated by Django 2.2.2 on 2019-06-22 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190623_0414'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
